### ISSUE TITLE
Why used nested backquote in byte-compiling-eval-after-load.md?

### ISSUE THREAD

**Issue by gavenkoa** [lunaryorn/blog#17]
In * The basic idea* you quote "function" docs and from:

    `(eval-after-load ',feature
       '(progn ,@forms))

jump to:

    `(eval-after-load ',feature
       `(funcall (function ,(lambda () ,@forms))))

Why?

`lambda` itself is a macro that surround *body* by `function`. This work just good:

    `(eval-after-load ',feature
       '(funcall (lambda () ,@forms)))

After your bug report http://debbugs.gnu.org/cgi/bugreport.cgi?bug=13021 Stefan enhence `eval-after-load` by:

    FORM can be an Elisp expression (in which case it's passed to `eval'),
    or a function (in which case it's passed to `funcall' with no argument).

so even `funcall` is unnecessary in your code, but this is not portable to Emacs 23.x ((

I like your idea for with- and ever look deeper into Emacs sources to understand Emacs internals after thinking about macroses http://emacs.stackexchange.com/questions/10485/order-of-evaluation-of-nested-macros-and-backquotes and byte compilation.

**Comment by gavenkoa** [comment]
Also Stefan introduce

   (declare (compiler-macro
            (lambda (whole)
              (if (eq 'quote (car-safe form))
                  ;; Quote with lambda so the compiler can look inside.
                  `(eval-after-load ,file (lambda () ,(nth 1 form)))
                whole))))

into `eval-after-load`  so it is unnecessary wrap into `lambda` *body* in your macros. Suddenly current implementation miss `with-no-warnings` and auto loading `feature`s during compilation to avoid noisy warnings.

**Comment by lunaryorn** [comment]
@gavenkoa No offense meant, but have you looked at the date of this post?  And compared it with the date of these changes in Emacs?  It was written before `eval-after-load` accepted function forms.

**Comment by gavenkoa** [comment]
Never mind! I start  journey into Emacs internals from your article when try to understand highlighted subject and problems, so wrote back my investigation to you in respect for your job to write article!
