### ISSUE TITLE
Horizontal scrollbar

### ISSUE THREAD

**Issue by aminb** [lunaryorn/blog#18]
I've recently noticed a horizontal scrollbar appearing on all pages (at least with Firefox and Chrome).

I don't exactly remember which commit introduced this, but applying these to `#navbar` is one way of getting rid of it:

```css
width: 98%;
padding-left: 2%;
padding-right: 0;
```

In other words, setting the padding in terms of percentage. However, since `em` is used throughout the whole stylesheet, maybe there's a "better" way, using `em`s? @lunaryorn

**Comment by lunaryorn** [comment]
Can you tell me the exact browser versions and your OS?  And could you show me a screenshot?

**Comment by aminb** [comment]
@lunaryorn Sure:

OS: Arch Linux
Kernel (not related but anyway): 3.17.7-1-ck
Firefox: 38.0.5
Chromium: Version 43.0.2357.81 (64-bit)

And screenshots after reverting your fix commit temporarily (using the inspector):
![lunaryorn-firefox](https://cloud.githubusercontent.com/assets/1254858/8084554/975a1af4-0f59-11e5-85f2-1493d7d74f3c.png)

![lunaryorn-chromium](https://cloud.githubusercontent.com/assets/1254858/8084565/a73f0c7c-0f59-11e5-96aa-c68713e005bd.png)

**Comment by lunaryorn** [comment]
I am inclined to blame the font configuration of your system.  I cannot reproduce this issue in Chrome or Firefox. FYI, that is how it looks for me:

![bildschirmfoto 2015-06-10 um 16 53 11](https://cloud.githubusercontent.com/assets/224922/8085615/560ac5c0-0f91-11e5-83d0-4e1655c5e48b.png)

I'm closing this as `wontfix`, since it's a corner case that I don't want to spend any time on trying to find out what goes wrong there.

**Comment by aminb** [comment]
@lunaryorn You're right, there is a problem with my fonts in the screenshots, and that's because my work place for some reason blocks `*.woff` files.

However, I also tried with my own connection, with the fonts rendering correctly, but without your fix commit, the problem still persists.

When using this theme for my website, I'll either use percentages for padding or just go with no horizontal padding as your fix does. Thanks for looking into this anyways.

**Comment by lunaryorn** [comment]
@aminb Yeah, but *with* my fix the issue is gone, isn't it?  

And well, if your work place blocks random files from my site, there's little I can do.  I don't want to open the kitchen sink of testing that site with random `serif` fonts…

**Comment by aminb** [comment]
@lunaryorn Yeah it *is* gone with the fix :)

And very true, I wouldn't want to do something like that either haha. Just mentioned that it used to be broken even with a *proper* internet connection.

Thanks again!
